from fpdf import FPDF
import os
import time

def generate_pdf_report(results):
    """
    Generate a simple PDF report from test results.
    
    Args:
        results: Dictionary containing test results
            - timestamp: When the test ran
            - search_name: Name that was searched for
            - role: Role assigned
            - found: Boolean - whether user was found
            - details: Additional details about the search
    
    Returns:
        str: Path to the generated PDF file
    """
    # Create PDF
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 15, "User Test Report", ln=True, align="C")
    pdf.ln(5)
    
    # Timestamp
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 8, f"Test Date: {results['timestamp']}", ln=True)
    pdf.ln(5)
    
    # Main Result - Big and Clear
    pdf.set_font("Arial", "B", 16)
    if results["found"]:
        pdf.set_text_color(0, 128, 0)  # Green
        pdf.cell(0, 12, f"[FOUND] {results['search_name']}", ln=True, align="C")
    else:
        pdf.set_text_color(255, 0, 0)  # Red
        pdf.cell(0, 12, f"[NOT FOUND] {results['search_name']}", ln=True, align="C")
    
    pdf.set_text_color(0, 0, 0)  # Back to black
    pdf.ln(5)
    
    # User Details Section
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "User Information:", ln=True)
    
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 7, f"  - Name: {results['search_name']}", ln=True)
    pdf.cell(0, 7, f"  - Role: {results['role']}", ln=True)
    pdf.ln(3)
    
    # Search Details Section
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Search Details:", ln=True)
    
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 7, f"  {results['details']}")
    
    # Footer
    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 5, "Generated by User Tester Automation Script", ln=True, align="C")
    
    # Save PDF
    report_dir = "test_reports"
    os.makedirs(report_dir, exist_ok=True)
    
    # Create filename with timestamp
    filename = f"user_test_{time.strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = os.path.join(report_dir, filename)
    
    pdf.output(file_path)
    
    return file_path